site_name: OSG Campus Research Documentation
site_url: https://opensciencegrid.github.io/campus-research/
repo_url: https://github.com/opensciencegrid/campus-research/
google_analytics: ['UA-69012-29', 'opensciencegrid.github.io']
theme:
  name: material
  custom_dir: osgthedocs
  favicon: 'img/favicon.ico'

extra_css:
  - css/extra.css

pages:
- Home: 'index.md'
- General:
  - 'CVMFS': 'general/cvmfs.md'
- Accounts and Groups:
  - 'General': 'accounts-and-projects/general.md'
  - 'Projects': 'accounts-and-projects/projects.md'
  - 'GoSync3': 'accounts-and-projects/gosync3.md'
- Midscale Engagements:
  - SPT:
    - 'General': 'midscale-experiments/spt/general.md'
    - 'CVMFS': 'midscale-experiments/spt/cvmfs.md'
  - VERITAS:
    - 'General': 'midscale-experiments/spt/general.md'
    - 'CVMFS': 'midscale-experiments/spt/cvmfs.md'
  - XENON:
    - 'General': 'midscale-experiments/spt/general.md'
    - 'CVMFS': 'midscale-experiments/spt/cvmfs.md'

markdown_extensions:
  - admonition
  - codehilite
  - toc:
     permalink: True
  - osg_markdown.colors
